### ISSUE TITLE
No module named 'newsapi'

### ISSUE THREAD

**Issue by Uddhav07** [Significant-Gravitas/Auto-GPT-Plugins#122]
WARNING: Plugin AutoGPTEmailPlugin found. But not in the allowlist... Load? (y/n): y
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\uvmit\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uvmit\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\uvmit\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uvmit\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uvmit\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uvmit\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Auto-GPT\autogpt\cli.py", line 90, in main
    run_auto_gpt(
  File "E:\Auto-GPT\autogpt\main.py", line 118, in run_auto_gpt
    cfg.set_plugins(scan_plugins(cfg, cfg.debug_mode))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Auto-GPT\autogpt\plugins.py", line 219, in scan_plugins
    zipped_module = zipped_package.load_module(str(module.parent))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen zipimport>", line 301, in load_module
  File "plugins\Auto-GPT-Plugins-master.zip\Auto-GPT-Plugins-master\src\autogpt_plugins\news_search\__init__.py", line 7, in <module>
  File "plugins\Auto-GPT-Plugins-master.zip\Auto-GPT-Plugins-master\src\autogpt_plugins\news_search\news_search.py", line 4, in <module>
ModuleNotFoundError: No module named 'newsapi'
Press any key to continue . . .

**Comment by duramaxlb7** [comment]
i have the same error, failure lines, but only when i run AutoGPT using Docker. when i initiate it via python locally, i am able to use news_search.



WARNING: Plugin AutoGPTBingSearch found. But not in the allowlist... Load? (y/n): n
WARNING: Plugin AutoGPTEmailPlugin found. But not in the allowlist... Load? (y/n): n
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/cli.py", line 90, in main
    run_auto_gpt(
  File "/app/autogpt/main.py", line 118, in run_auto_gpt
    cfg.set_plugins(scan_plugins(cfg, cfg.debug_mode))
  File "/app/autogpt/plugins.py", line 219, in scan_plugins
    zipped_module = zipped_package.load_module(str(module.parent))
  File "<frozen zipimport>", line 302, in load_module
  File "plugins/Auto-GPT-Plugins.zip/Auto-GPT-Plugins-master/src/autogpt_plugins/news_search/__init__.py", line 7, in <module>
  File "plugins/Auto-GPT-Plugins.zip/Auto-GPT-Plugins-master/src/autogpt_plugins/news_search/news_search.py", line 4, in <module>

**Comment by dje3392** [comment]
Same issue, I tried attaching to the docker container and running a `pip install newsapi` but that returned another error: 

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/cli.py", line 90, in main
    run_auto_gpt(
  File "/app/autogpt/main.py", line 118, in run_auto_gpt
    cfg.set_plugins(scan_plugins(cfg, cfg.debug_mode))
  File "/app/autogpt/plugins.py", line 219, in scan_plugins
    zipped_module = zipped_package.load_module(str(module.parent))
  File "<frozen zipimport>", line 302, in load_module
  File "plugins/Auto-GPT-Plugins.zip/Auto-GPT-Plugins-master/src/autogpt_plugins/news_search/__init__.py", line 7, in <module>
  File "plugins/Auto-GPT-Plugins.zip/Auto-GPT-Plugins-master/src/autogpt_plugins/news_search/news_search.py", line 4, in <module>
ImportError: cannot import name 'NewsApiClient' from 'newsapi' (/usr/local/lib/python3.10/site-packages/newsapi/__init__.py)

**Comment by Blackosss** [comment]
I followed these steps someone on discord posted and it solved the issue for me:

Premium Algorithm — 05/04/2023 8:07 PM
best bet is to use GPT4 to walk you through it as it was a bit confusing, that being said i added: 

COPY requirements.txt /workspace/Auto-GPT/
RUN pip install --no-cache-dir -r requirements.txt newsapi-python
RUN pip install lorem
to the end of the dockerfile
also
added:

#NewsAPI
newsapi-python

#Lorem
lorem==0.1.1

to the requirements file

then you rebuild your image using this command:
docker-compose build auto-gpt
docker-compose run --rm auto-gpt

**Comment by kevin-huff** [comment]
> COPY requirements.txt /workspace/Auto-GPT/ RUN pip install --no-cache-dir -r requirements.txt newsapi-python RUN pip install lorem to the end of the dockerfile also added:
> 
> #NewsAPI newsapi-python
> 
> #Lorem lorem==0.1.1
> 
> to the requirements file
> 
> then you rebuild your image using this command: docker-compose build auto-gpt docker-compose run --rm auto-gpt

works for me. a bit of effort to press -n on it but got it running at least.

**Comment by ntindle** [comment]
fixed
