### ISSUE TITLE
New Errors after AutoGPT Update

### ISSUE THREAD

**Issue by MastQ** [Significant-Gravitas/Auto-GPT-Plugins#194]
Firstly thank you for developing this code, it has lot of potential for traders.  I am getting the error below can you help me resolvve it please.  It was working fine yesterdat  Thank you and sorry for troubling you if i am getting this error due to an amterut mistake.

WARNING: Plugin AutoGPTMetaTraderPlugin found. But not in the allowlist... Load? (y/n): y
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\alpha\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alpha\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\alpha\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alpha\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alpha\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alpha\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Auto-GPT\autogpt\cli.py", line 96, in main
    run_auto_gpt(
  File "C:\Auto-GPT\autogpt\main.py", line 142, in run_auto_gpt
    cfg.set_plugins(scan_plugins(cfg, cfg.debug_mode))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Auto-GPT\autogpt\plugins.py", line 238, in scan_plugins
    loaded_plugins.append(a_module())
                          ^^^^^^^^^^
  File "C:\Users\alpha\AppData\Local\Programs\Python\Python311\Lib\site-packages\abstract_singleton\__init__.py", line 14, in __call__
    cls._instances[cls] = super().__call__(*args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Can't instantiate abstract class AutoGPTMetaTraderPlugin with abstract methods can_handle_report, can_handle_text_embedding, can_handle_user_input, handle_text_embedding, report, user_input

**Comment by AaronGoldsmith1** [comment]
Im getting a similar error when trying to run the install script:

`TypeError: Can't instantiate abstract class AutoGPTTelegram with abstract methods can_handle_text_embedding, handle_text_embedding`

**Comment by Luxguild** [comment]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/gcg/gpt/v2/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gcg/gpt/v2/Auto-GPT/autogpt/cli.py", line 96, in main
    run_auto_gpt(
  File "/Users/gcg/gpt/v2/Auto-GPT/autogpt/main.py", line 142, in run_auto_gpt
    cfg.set_plugins(scan_plugins(cfg, cfg.debug_mode))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gcg/gpt/v2/Auto-GPT/autogpt/plugins.py", line 227, in scan_plugins
    zipped_module = zipped_package.load_module(str(module.parent))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen zipimport>", line 301, in load_module
  File "plugins/Auto-GPT-Plugins.zip/Auto-GPT-Plugins-master/src/autogpt_plugins/telegram/__init__.py", line 8, in <module>
  File "plugins/Auto-GPT-Plugins.zip/Auto-GPT-Plugins-master/src/autogpt_plugins/telegram/telegram_chat.py", line 7, in <module>
ImportError: cannot import name 'TimedOut' from 'telegram.error' (/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telegram/error.py)

**Comment by n0kovo** [comment]
Same
