### ISSUE TITLE
Auto-gpt plugins Telegram ImportError: cannot import name 'TimedOut' from 'telegram.error' 

### ISSUE THREAD

**Issue by Luxguild** [Significant-Gravitas/Auto-GPT-Plugins#196]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/gcg/gpt/v2/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gcg/gpt/v2/Auto-GPT/autogpt/cli.py", line 96, in main
    run_auto_gpt(
  File "/Users/gcg/gpt/v2/Auto-GPT/autogpt/main.py", line 142, in run_auto_gpt
    cfg.set_plugins(scan_plugins(cfg, cfg.debug_mode))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gcg/gpt/v2/Auto-GPT/autogpt/plugins.py", line 227, in scan_plugins
    zipped_module = zipped_package.load_module(str(module.parent))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen zipimport>", line 301, in load_module
  File "plugins/Auto-GPT-Plugins.zip/Auto-GPT-Plugins-master/src/autogpt_plugins/telegram/__init__.py", line 8, in <module>
  File "plugins/Auto-GPT-Plugins.zip/Auto-GPT-Plugins-master/src/autogpt_plugins/telegram/telegram_chat.py", line 7, in <module>
ImportError: cannot import name 'TimedOut' from 'telegram.error' (/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telegram/error.py)

**Comment by Wladastic** [comment]
seems like the wrong telegram package is installed, which one do you have installed?
