### ISSUE TITLE
Problem installing the dependencies for the plugins on win10 on a fresh autogpt clone

### ISSUE THREAD

**Issue by KaptainKeelhaul** [Significant-Gravitas/Auto-GPT-Plugins#215]
When cloning AutoGPT and then trying to introduce the plugins, the update dependencies step fail:

.\run.bat --install-plugin-deps

It gives this output:

`ModuleNotFoundError: No module named 'validators'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\repos\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\tedli\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tedli\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\tedli\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1666, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tedli\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tedli\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tedli\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\repos\Auto-GPT\autogpt\cli.py", line 117, in main
    run_auto_gpt(
  File "C:\repos\Auto-GPT\autogpt\main.py", line 131, in run_auto_gpt
    config.plugins = scan_plugins(config, config.debug_mode)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\repos\Auto-GPT\autogpt\plugins\__init__.py", line 261, in scan_plugins
    zipped_module = zipped_package.load_module(str(module.parent))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen zipimport>", line 301, in load_module
  File "plugins\Auto-GPT-Plugins.zip\Auto-GPT-Plugins-master\src\autogpt_plugins\api_tools\__init__.py", line 9, in <module>
ModuleNotFoundError: No module named 'api_tools'`

Going to investigate it more

**Comment by srkn-ts** [comment]
Same here.

**Comment by tlok666** [comment]
Same issue!

**Comment by jameswhand** [comment]
Me too!

**Comment by jameswhand** [comment]
How to fix it? I faced the same issue and just can't use any plugin.

**Comment by jameswhand** [comment]
> When cloning AutoGPT and then trying to introduce the plugins, the update dependencies step fail:
> 
> .\run.bat --install-plugin-deps
> 
> It gives this output:
> 
> `ModuleNotFoundError: No module named 'validators'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "", line 198, in _run_module_as_main File "", line 88, in _run_code File "C:\repos\Auto-GPT\autogpt__main__.py", line 5, in autogpt.cli.main() File "C:\Users\tedli\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1157, in **call** return self.main(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\tedli\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1078, in main rv = self.invoke(ctx) ^^^^^^^^^^^^^^^^ File "C:\Users\tedli\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1666, in invoke rv = super().invoke(ctx) ^^^^^^^^^^^^^^^^^^^ File "C:\Users\tedli\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 1434, in invoke return ctx.invoke(self.callback, **ctx.params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\tedli\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\core.py", line 783, in invoke return __callback(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\tedli\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\decorators.py", line 34, in new_func return f(get_current_context(), *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\repos\Auto-GPT\autogpt\cli.py", line 117, in main run_auto_gpt( File "C:\repos\Auto-GPT\autogpt\main.py", line 131, in run_auto_gpt config.plugins = scan_plugins(config, config.debug_mode) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\repos\Auto-GPT\autogpt\plugins__init__.py", line 261, in scan_plugins zipped_module = zipped_package.load_module(str(module.parent)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 301, in load_module File "plugins\Auto-GPT-Plugins.zip\Auto-GPT-Plugins-master\src\autogpt_plugins\api_tools__init__.py", line 9, in ModuleNotFoundError: No module named 'api_tools'`
> 
> Going to investigate it more

Man, I figured this out. You have to unzip the main zip file under the "./plugins" folder, for me it is the "Auto-GPT-Plugins.zip", then find the "requirements.txt" in the unzipped folder, and run "pip install -r requirements.txt" to install these dependencies manually!
