### ISSUE TITLE
Latest Code isn't running.

### ISSUE THREAD

**Issue by jeffreycam** [Significant-Gravitas/Auto-GPT-Plugins#59]
Hello, I have downloaded auto-gpt, & auto-gpt plugins, and all seem to be configured correctly. I have an earlier version running without  issue. I can't get auto-gpt to run because of this error.

The command I'm executing per instructions:
.\run.bat --install-plugin-deps

ERROR MESSAGE:   **File "C:\Users\jeffr\AppData\Local\Programs\Python\Python310\lib\site-packages\abstract_singleton\__init__.py", line 14, in __call__
    cls._instances[cls] = super().__call__(*args, **kwargs)
  File "plugins\Auto-GPT-Plugins.zip\Auto-GPT-Plugins-master\src\autogpt_plugins\twitter\__init__.py", line 41, in __init__**

The complete output I received is: (scroll to the bottom to see the error)
PS D:\ai-autogpt\Auto-GPT-master> .\run.bat --install-plugin-deps
All packages are installed.
NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here. If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag # INCLUDED COMMAND 'send_tweet' IS DEPRICATED, AND WILL BE REMOVED IN THE NEXT STABLE RELEASE Base Twitter functionality (and more) is now covered by plugins: https://github.com/Significant-Gravitas/Auto-GPT-Plugins ## Changes to Docker configuration The workdir has been changed from /home/appuser to /app.
 Be sure to update any volume mounts accordingly.
Requirement already satisfied: black in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from -r plugins\Auto-GPT-Plugins-master\requirements.txt (line 1)) (23.3.0)
Requirement already satisfied: isort in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from -r plugins\Auto-GPT-Plugins-master\requirements.txt (line 2)) (5.12.0)
Requirement already satisfied: flake8 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from -r plugins\Auto-GPT-Plugins-master\requirements.txt (line 3)) (6.0.0)
Requirement already satisfied: pylint in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from -r plugins\Auto-GPT-Plugins-master\requirements.txt (line 4)) (2.17.3)
Requirement already satisfied: abstract-singleton in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from -r plugins\Auto-GPT-Plugins-master\requirements.txt (line 5)) (1.0.1)
Requirement already satisfied: wheel in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from -r plugins\Auto-GPT-Plugins-master\requirements.txt (line 6)) (0.40.0)
Requirement already satisfied: setuptools in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from -r plugins\Auto-GPT-Plugins-master\requirements.txt (line 7)) (65.5.0)
Requirement already satisfied: build in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from -r plugins\Auto-GPT-Plugins-master\requirements.txt (line 8)) (0.10.0)
Requirement already satisfied: twine in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from -r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (4.0.2)
Requirement already satisfied: tweepy in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from -r plugins\Auto-GPT-Plugins-master\requirements.txt (line 10)) (4.14.0)
Requirement already satisfied: pandas in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from -r plugins\Auto-GPT-Plugins-master\requirements.txt (line 11)) (2.0.1)
Requirement already satisfied: auto_gpt_plugin_template in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from -r plugins\Auto-GPT-Plugins-master\requirements.txt (line 12)) (0.0.3)
Requirement already satisfied: click>=8.0.0 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from black->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 1)) (8.1.3)
Requirement already satisfied: mypy-extensions>=0.4.3 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from black->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 1)) (1.0.0)
Requirement already satisfied: packaging>=22.0 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from black->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 1)) (23.1)
Requirement already satisfied: pathspec>=0.9.0 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from black->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 1)) (0.11.1)
Requirement already satisfied: platformdirs>=2 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from black->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 1)) (3.2.0)
Requirement already satisfied: tomli>=1.1.0 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from black->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: mccabe<0.8.0,>=0.7.0 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from flake8->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 3)) (0.7.0)
Requirement already satisfied: pycodestyle<2.11.0,>=2.10.0 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from flake8->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 3)) (2.10.0)
Requirement already satisfied: pyflakes<3.1.0,>=3.0.0 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from flake8->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 3)) (3.0.1)
Requirement already satisfied: astroid<=2.17.0-dev0,>=2.15.4 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from pylint->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 4)) (2.15.4)
Requirement already satisfied: tomlkit>=0.10.1 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from pylint->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 4)) (0.11.7)
Requirement already satisfied: dill>=0.2 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from pylint->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 4)) (0.3.6)
Requirement already satisfied: colorama>=0.4.5 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from pylint->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 4)) (0.4.6)
Requirement already satisfied: pyproject_hooks in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from build->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 8)) (1.0.0)
Requirement already satisfied: pkginfo>=1.8.1 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from twine->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (1.9.6)
Requirement already satisfied: readme-renderer>=35.0 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from twine->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (37.3)
Requirement already satisfied: requests>=2.20 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from twine->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (2.28.2)
Requirement already satisfied: requests-toolbelt!=0.9.0,>=0.8.0 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from twine->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (0.10.1)
Requirement already satisfied: urllib3>=1.26.0 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from twine->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (1.26.15)
Requirement already satisfied: importlib-metadata>=3.6 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from twine->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (6.6.0)
Requirement already satisfied: keyring>=15.1 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from twine->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (23.13.1)
Requirement already satisfied: rfc3986>=1.4.0 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from twine->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (2.0.0)
Requirement already satisfied: rich>=12.0.0 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from twine->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (13.3.4)
Requirement already satisfied: oauthlib<4,>=3.2.0 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from tweepy->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 10)) (3.2.2)
Requirement already satisfied: requests-oauthlib<2,>=1.2.0 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from tweepy->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 10)) (1.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from pandas->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 11)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from pandas->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 11)) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from pandas->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 11)) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from pandas->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 11)) (1.24.2)
Requirement already satisfied: lazy-object-proxy>=1.4.0 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from astroid<=2.17.0-dev0,>=2.15.4->pylint->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 4)) (1.9.0)
Requirement already satisfied: wrapt<2,>=1.11 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from astroid<=2.17.0-dev0,>=2.15.4->pylint->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 4)) (1.15.0)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from astroid<=2.17.0-dev0,>=2.15.4->pylint->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 4)) (4.5.0)
Requirement already satisfied: zipp>=0.5 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from importlib-metadata>=3.6->twine->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (3.15.0)
Requirement already satisfied: jaraco.classes in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from keyring>=15.1->twine->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (3.2.3)
Requirement already satisfied: pywin32-ctypes>=0.2.0 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from keyring>=15.1->twine->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (0.2.0)
Requirement already satisfied: six>=1.5 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 11)) (1.16.0)
Requirement already satisfied: bleach>=2.1.0 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from readme-renderer>=35.0->twine->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (6.0.0)
Requirement already satisfied: docutils>=0.13.1 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from readme-renderer>=35.0->twine->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (0.19)
Requirement already satisfied: Pygments>=2.5.1 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from readme-renderer>=35.0->twine->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (2.15.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.20->twine->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.20->twine->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.20->twine->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (2022.12.7)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from rich>=12.0.0->twine->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (2.2.0)
Requirement already satisfied: webencodings in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from bleach>=2.1.0->readme-renderer>=35.0->twine->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (0.5.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=12.0.0->twine->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (0.1.2)
Requirement already satisfied: more-itertools in c:\users\jeffr\appdata\local\programs\python\python310\lib\site-packages (from jaraco.classes->keyring>=15.1->twine->-r plugins\Auto-GPT-Plugins-master\requirements.txt (line 9)) (9.1.0)
Traceback (most recent call last):
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\ai-autogpt\Auto-GPT-master\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python310\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "D:\ai-autogpt\Auto-GPT-master\autogpt\cli.py", line 90, in main
    run_auto_gpt(
  File "D:\ai-autogpt\Auto-GPT-master\autogpt\main.py", line 104, in run_auto_gpt
    cfg.set_plugins(scan_plugins(cfg, cfg.debug_mode))
  File "D:\ai-autogpt\Auto-GPT-master\autogpt\plugins.py", line 229, in scan_plugins
    loaded_plugins.append(a_module())
  File "C:\Users\jeffr\AppData\Local\Programs\Python\Python310\lib\site-packages\abstract_singleton\__init__.py", line 14, in __call__
    cls._instances[cls] = super().__call__(*args, **kwargs)
  File "plugins\Auto-GPT-Plugins.zip\Auto-GPT-Plugins-master\src\autogpt_plugins\twitter\__init__.py", line 41, in __init__
AttributeError: module 'tweepy' has no attribute 'Stream'
Press any key to continue . . .

**Comment by jeffreycam** [comment]
Sorry, I didn't give the complete error message: 
**File "plugins\Auto-GPT-Plugins.zip\Auto-GPT-Plugins-master\src\autogpt_plugins\twitter_init.py", line 41, in init
AttributeError: module 'tweepy' has no attribute 'Stream'**

**Comment by jeffreycam** [comment]
I wrote a better post for my issue.
